### ISSUE TITLE
[question] Compatible / Preferred M:N threading libs?

### ISSUE THREAD

**Issue by complyue** [Marthog/rust-stm#12]
Hi, I hope it's proper to file this issue to ask here:

I'd like to know which M:N threading lib or libs in Rust will this STM implementation be compatible with? Preference ? Or only the std lib's 1:1 thread ?

I have never worked with Rust before, so have difficulties to figure out on my own, and couldn't find clues from this project's description.

The background is that I'm considering to port one of my old FUSE filesystem based array database controller from Go (open source part at https://github.com/complyue/jdfs) to Rust, while at the same time port https://github.com/e-wrks/edh to Rust as the interpreter for comm between db clients and the controller. Edh makes extensive use of STM in Haskell, as well as the lightweight threads to implement goroutine like constructs. It won't be possible without STM plus an M:N threading lib working together sufficiently well.

**Comment by Marthog** [comment]
Hello,

this library uses parking_lot, which is designed for OS threads. I am not aware of any M:N threading libraries, that are compatible with it.

**Comment by complyue** [comment]
Thanks for the info.
